# Stage 1: Build the Angular app
FROM node:18.10-alpine as build
WORKDIR /app
COPY my-app/package.json my-app/package-lock.json ./
WORKDIR /app/my-app
RUN npm install
COPY my-app/. .
RUN npm run build

# Stage 2: Serve the built app with Nginx
FROM nginx:1.21-alpine
COPY --from=build /app/my-app/dist/my-app /usr/share/nginx/html
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]